version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: deepFM_experiment
    volumes:
      - '../:/workspace'
    container_name: deepFM_experiment
    tty: true
    working_dir: '/workspace'